In [2]:
featVec = [1,2,3,'yes']
featVec[-1]

'yes'

In [7]:
#log
from math import log
?log()
-2/5*log(2/5,2)-3/5*log(3/5,2)

0.9709505944546686

In [4]:
#append and extend 
a=c=[1,2,3] 
b=d=[4,5,6]
a.append(b)
a
c.extend(d)
c #a变c也变了

[1, 2, 3, [4, 5, 6]]

[1, 2, 3, [4, 5, 6], 4, 5, 6]

In [8]:
# set 
dataset=[[1,1,'yes'],[1,1,'yes'],[1,0,'no'],[0,1,'no'],[0,1,'no']]
numfeatures=len(dataset[0])-1
for i in range(numfeatures):
    featlist=[example[i] for example in dataset]
    uniquevals = set(featlist) #集合
    featlist
    uniquevals

[1, 1, 1, 0, 0]

{0, 1}

[1, 1, 0, 1, 1]

{0, 1}

In [33]:
#sort with one element in dict 
import operator
dataset=[[1,1,'yes'],[1,1,'yes'],[1,1,'yes'],[1,0,'pp'],[0,1,'no'],[0,1,'no']]
classlist=[example[-1] for example in dataset]
classcount = {}
for vote in classlist:
    if vote not in classcount.keys():
        classcount[vote]=0
    classcount[vote]+=1
classcount
classcount.items()
sortedclasscount=sorted(classcount.items(),key=operator.itemgetter(0),reverse=True)
sortedclasscount
sortedclasscount=sorted(classcount.items(),key=operator.itemgetter(1),reverse=True)
sortedclasscount
?operator.itemgetter()

{'no': 2, 'pp': 1, 'yes': 3}

dict_items([('yes', 3), ('pp', 1), ('no', 2)])

[('yes', 3), ('pp', 1), ('no', 2)]

[('yes', 3), ('no', 2), ('pp', 1)]

In [38]:
#copy and del a dict 
labels=['a','b','c','d']
anotherlabels = labels[:]
del(labels[0])
labels
anotherlabels

['b', 'c', 'd']

['a', 'b', 'c', 'd']

In [2]:
# eye() shape()
from numpy import *
dataset=mat(eye(4))
dataset
eye(4)
a = [[1,2]]
m=shape(a)[1]
m

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

2

In [17]:
# extract value in list 
dataset[:,1]
dataset[:,1]<0.5
nonzero(dataset[:,1]<0.5)
nonzero(dataset[:,1]<0.5)[0]
dataset[nonzero(dataset[:,1]<0.5)[0],:]
dataset[nonzero(dataset[:,1]<0.5)[0],:][0]

matrix([[0.],
        [1.],
        [0.],
        [0.]])

matrix([[ True],
        [False],
        [ True],
        [ True]])

(array([0, 2, 3]), array([0, 0, 0]))

array([0, 2, 3])

matrix([[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

matrix([[1., 0., 0., 0.]])

In [2]:
# linalg 线性代数库 linalg.det（）
from numpy import *
?linalg.det()

In [5]:
# 将matrix或array元素折叠成一维的
a=mat([[1,2,3],[4,5,6]])
a.flatten()
b=array([[1,2],[3,4],[5,6]])
b.flatten()

matrix([[1, 2, 3, 4, 5, 6]])

array([1, 2, 3, 4, 5, 6])

In [16]:
?mean()
?var（）
zeros((3,1))
a = inf
a
b = mat([[1,2,3],[4,5,6]])
b
b.A

array([[0.],
       [0.],
       [0.]])

inf

matrix([[1, 2, 3],
        [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [44]:
#堆叠数组
c = tile([-2,-1],(3,2))
c
c=c**2
c
c.sum(axis=1)
c.sum(axis=0)

array([[-2, -1, -2, -1],
       [-2, -1, -2, -1],
       [-2, -1, -2, -1]])

array([[4, 1, 4, 1],
       [4, 1, 4, 1],
       [4, 1, 4, 1]])

array([10, 10, 10])

array([12,  3, 12,  3])

In [30]:
d=array([0,0])-array([1,1])
d

array([-1, -1])

In [37]:
?sum()